### ISSUE TITLE
Platform Exception

### ISSUE THREAD

**Issue by yeminsoe** [dns-technologies/mlkit_scanner#11]
First of all, I would like to thank you for your doing this plugin. 
I am problem a bite when I run on Physical Device iOS.
I faced like the following image. Could I need to do anything for this?
<img width="266" alt="Screen Shot 2022-09-16 at 9 35 41 AM" src="https://user-images.githubusercontent.com/34262011/190548830-7962ce8e-9939-45d8-aad1-2a2b3d20d591.png">

**Comment by skrjt** [comment]
Hi, @yeminsoe !
Error 2 - this error occurs when the application does not have permission to use the camera.
For ios needs to add `ios/Runner/Info.plist`:
```
<key>NSCameraUsageDescription</key>
<description>Appropriate permission is required to initialize the camera</description>
```

If the problem persists, please describe your actions to get this error.
Also, is there a similar error when using our example?

**Comment by Soliardi-Chyngyz** [comment]
> Hi, @yeminsoe ! Error 2 - this error occurs when the application does not have permission to use the camera. For ios needs to add `ios/Runner/Info.plist`:
> 
> ```
> <key>NSCameraUsageDescription</key>
> <description>Appropriate permission is required to initialize the camera</description>
> ```
> 
> If the problem persists, please describe your actions to get this error. Also, is there a similar error when using our example?

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method updateConstraints on channel mlkit_channel)
E/flutter (18265): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (18265): <asynchronous suspension>

**Comment by skrjt** [comment]
@Soliardi-Chyngyz , hi!

I was unable to reproduce this error. Can you provide more information on how it can be reproduced? Also, I'm not sure if this applies to this issue, so I suggest you create a new one with a detail description.

**Comment by skrjt** [comment]
Closed due to no response
