### ISSUE TITLE
CameraViewFactory.kt

### ISSUE THREAD

**Issue by sahilgarg156** [dns-technologies/mlkit_scanner#2]
.../Flutter SDK/flutter_3.0.0/.pub-cache/hosted/pub.dartlang.org/mlkit_scanner-0.2.0/android/src/main/kotlin/com/dns_technologies/mlkit_scanner/CameraViewFactory.kt: (14, 5): 'create' overrides nothing

For iOS working fine but For android it given above error.
Thanks in advance

**Comment by grebennikovlmax** [comment]
Issue has fixed in version 3.0.0.
